[package]
name = "minigrep_hw"
version = "0.1.0"
edition = "2024"

[dependencies]
hyperscan-sys = { version = "0.3", features = ["compile"] }
anyhow = "1.0"

[profile.release] 
opt-level = 3
lto = "fat"